apiVersion: v1
kind: Secret
metadata:
  name: mariadb-config
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: adventcalendar
  MYSQL_USER: adventcalendar
  MYSQL_PASSWORD: adventcalendar
type: Opaque
