apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-consumer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: email-consumer
    spec:
      restartPolicy: Always
      containers:
        - image: registry.adamkoro.com/adventcalendar/backend/email-consumer:latest
          imagePullPolicy: Always
          name: email-consumer
          resources:
            requests:
              cpu: "300m"
              memory: "100M"
            limits:
              cpu: "2000m"
              memory: "200M"
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: http-api
              protocol: TCP
            - containerPort: 8081
              name: http-metrics
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_VHOST
              value: "/"
          envFrom:
            - secretRef:
                name: smtp-config
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
