kind: Service
apiVersion: v1
metadata:
  name: email-consumer
spec:
  selector:
    app: email-consumer
  ports:
    - name: http
      port: 80
      targetPort: http-api
    - name: metrics
      port: 81
      targetPort: http-metrics
