kind: pipeline
name: build-backend
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: admin-api
  image: plugins/docker
  settings:
    username:
      from_secret: registry_user
    password:
      from_secret: registry_password
    registry: registry.adamkoro.com
    repo: registry.adamkoro.com/adventcalendar/backend/admin-api
    dockerfile: admin-api/Dockerfile
    context: .
    purge: false
    tags:
    - latest
    platform: 
    - linux/amd64

- name: auth-api-init
  image: plugins/docker
  settings:
    username:
      from_secret: registry_user
    password:
      from_secret: registry_password
    registry: registry.adamkoro.com
    repo: registry.adamkoro.com/adventcalendar/backend/auth-api-init
    dockerfile: auth-api-init/Dockerfile
    context: .
    purge: false
    tags:
    - latest
    platform: 
    - linux/amd64

- name: auth-api
  image: plugins/docker
  settings:
    username:
      from_secret: registry_user
    password:
      from_secret: registry_password
    registry: registry.adamkoro.com
    repo: registry.adamkoro.com/adventcalendar/backend/auth-api
    dockerfile: auth-api/Dockerfile
    context: .
    purge: false
    tags:
    - latest
    platform: 
    - linux/amd64

- name: publisher-api-init
  image: plugins/docker
  settings:
    username:
      from_secret: registry_user
    password:
      from_secret: registry_password
    registry: registry.adamkoro.com
    repo: registry.adamkoro.com/adventcalendar/backend/publisher-init
    dockerfile: email-api/publisher-init/Dockerfile
    context: .
    purge: false
    tags:
    - latest
    platform: 
    - linux/amd64

- name: publisher-api
  image: plugins/docker
  settings:
    username:
      from_secret: registry_user
    password:
      from_secret: registry_password
    registry: registry.adamkoro.com
    repo: registry.adamkoro.com/adventcalendar/backend/publisher
    dockerfile: email-api/publisher/Dockerfile
    context: .
    purge: false
    tags:
    - latest
    platform: 
    - linux/amd64

- name: consumer
  image: plugins/docker
  settings:
    username:
      from_secret: registry_user
    password:
      from_secret: registry_password
    registry: registry.adamkoro.com
    repo: registry.adamkoro.com/adventcalendar/backend/consumer
    dockerfile: email-api/consumer/Dockerfile
    context: .
    purge: false
    tags:
    - latest
    platform: 
    - linux/amd64

- name: public-api
  image: plugins/docker
  settings:
    username:
      from_secret: registry_user
    password:
      from_secret: registry_password
    registry: registry.adamkoro.com
    repo: registry.adamkoro.com/adventcalendar/backend/public-api
    dockerfile: public-api/Dockerfile
    context: .
    purge: false
    tags:
    - latest
    platform: 
    - linux/amd64

node:
  type: hosted-amd64