kind: template
load: adventcalendar-backend-build.yaml
data:
  components:
    - input:
        componentName: admin-api
        dockerfile: admin-api/Dockerfile
    - input:
        componentName: auth-api-init
        dockerfile: auth-api-init/Dockerfile
    - input:
        componentName: auth-api
        dockerfile: auth-api/Dockerfile
    - input:
        componentName: email-publisher-init
        dockerfile: email-api/publisher-init/Dockerfile
    - input:
        componentName: email-publisher
        dockerfile: email-api/publisher/Dockerfile
    - input:
        componentName: email-consumer
        dockerfile: email-api/consumer/Dockerfile
    - input:
        componentName: public-api
        dockerfile: public-api/Dockerfile
