kind: template
load: adventcalendar-backend-build.yaml
data:
    components:
    - input:
        linodeType: g6-standard-1
        linodeRegion: it-mil
        componentName: admin-api
        dockerfile: admin-api/Dockerfile
    - input:
<<<<<<< HEAD
        componentName: auth-api-init
        dockerfile: auth-api-init/Dockerfile
    - input:
        componentName: auth-api
        dockerfile: auth-api/Dockerfile
=======
        linodeType: g6-standard-1
        linodeRegion: it-mil
        componentName: admin-auth-init
        dockerfile: admin-auth-init/Dockerfile
    - input:
        linodeType: g6-standard-1
        linodeRegion: it-mil
        componentName: admin-auth
        dockerfile: admin-auth/Dockerfile
>>>>>>> 328f8a0 (ci: new variables)
    - input:
        linodeType: g6-standard-1
        linodeRegion: it-mil
        componentName: email-publisher-init
        dockerfile: email-api/publisher-init/Dockerfile
    - input:
        linodeType: g6-standard-1
        linodeRegion: it-mil
        componentName: email-publisher
        dockerfile: email-api/publisher/Dockerfile
    - input:
        linodeType: g6-standard-1
        linodeRegion: it-mil
        componentName: email-consumer
        dockerfile: email-api/consumer/Dockerfile
    - input:
        linodeType: g6-standard-1
        linodeRegion: it-mil
        componentName: public-api
        dockerfile: public-api/Dockerfile
