kind: pipeline
name: build-backend
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  environment:
    REGISTRY_USER:
      from_secret: registry_user
    REGISTRY_PASS:
      from_secret: registry_password
  settings:
    username: ${REGISTRY_USER}
    password: ${REGISTRY_PASS}
    registry: registry.adamkoro.com
    repo: registry.adamkoro.com/adventcalendar/backend/admin-api
    dockerfile: admin-api/Dockerfile
    context: .
    tags:
    - latest
    platform: 
    - linux/amd64

node:
  type: hosted-amd64