apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: public-api
    spec:
      restartPolicy: Always
      containers:
        - image: registry.adamkoro.com/adventcalendar/backend/public-api:latest
          imagePullPolicy: Always
          name: public-api
          resources:
            requests:
              cpu: "300m"
              memory: "100M"
            limits:
              cpu: "2000m"
              memory: "200M"
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: http-api
              protocol: TCP
            - containerPort: 8081
              name: http-metrics
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret-key
                  key: SECRET_KEY
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-config
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-config
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: DB_HOST
              value: "mongo"
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-config
                  key: MONGO_INITDB_DATABASE
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
