kind: Service
apiVersion: v1
metadata:
  name: public-api
spec:
  selector:
    app: public-api
  ports:
    - name: api
      port: 80
      targetPort: http-api
    - name: metrics
      port: 81
      targetPort: http-metrics
