version: "3.7"
services:
  # AdventCalendar-Backend
  staging-adventcalendar-backend:
    build:
      context: ../../admin-api/
      dockerfile: Dockerfile
    container_name: staging-adventcalendar-backend
    environment:
      - "DB_HOST=dev-postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
      - "RABBITMQ_HOST=dev-rabbitmq"
      - "RABBITMQ_USER=rabbitmq"
      - "RABBITMQ_PASSWORD=rabbitmq"
      - "REDIS_HOST=dev-redis"
      - "REDIS_DB=0"
    ports:
      - "8080:8080"
      - "8081:8081"
  # Postgres
  staging-postgres:
    image: docker.io/postgres:15.4-alpine
    container_name: staging-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adventcalendar
  # RabbitMQ
  staging-rabbitmq:
    image: docker.io/rabbitmq:3.12.4-management-alpine
    container_name: staging-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
  # Redis
  staging-redis:
    image: docker.io/redis:7.2.0-alpine
    container_name: staging-redis
    ports:
      - "6379:6379"
  staging-prometheus:
    image: docker.io/prom/prometheus:v2.46.0
    container_name: staging-prometheus
    ports:
      - "9090:9090"
    #volumes:
    #  - ./prometheus.yml:/etc/prometheus/prometheus.yml
  staging-grafana:
    image: docker.io/grafana/grafana:10.1.0
    container_name: staging-grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: GrafanaViewer
      GF_AUTH_ANONYMOUS_ORG_NAME: AdventCalendar
      GF_AUTH_ANONYMOUS_ORG_ID: 1
    #volumes:
    #  - ./grafana/provisioning:/etc/grafana/provisioning
    #  - ./grafana/dashboards:/var/lib/grafana/dashboards
networks:
  default:
    name: staging-adventcalendar