apiVersion: v1
kind: Service
metadata:
  name: rabbitmq 
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      name: rabbitmq-amqp
      targetPort: rabbitmq-amqp
    - port: 15672
      name: rabbitmq-http
      targetPort: rabbitmq-http
  clusterIP: None