kind: Service
apiVersion: v1
metadata:
  name: auth-api
spec:
  selector:
    app: auth-api
  ports:
    - name: http
      port: 80
      targetPort: http-api
    - name: metrics
      port: 81
      targetPort: http-metrics
