apiVersion: apps/v1
kind: Deployment
metadata:
  name:  admin-api
spec:
  replicas:  1
  selector:
    matchLabels:
      app:  admin-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  admin-api
    spec:
      restartPolicy: Always
      initContainers:
        - name: init-db
          image: registry.adamkoro.com/adventcalendar/backend/admin-api-init:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: postgres-database-auth
            - secretRef:
                name: admin-user-auth
      containers:
      - image:  registry.adamkoro.com/adventcalendar/backend/admin-api:latest
        imagePullPolicy: Always
        name:  admin-api
        resources:
          requests:
            cpu: "300m"
            memory: "100M"
          limits:
            cpu: "2000m"
            memory: "200M"
        livenessProbe:
          httpGet:
            path: /api/ping
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/ping
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5     
        ports:
        - containerPort:  8080
          name:  http-api
          protocol: TCP
        - containerPort:  8081
          name:  http-metrics
          protocol: TCP
        env:
        - name: LOG_LEVEL
          value:  "info"
        - name:  SECRET_KEY
          valueFrom:
            secretKeyRef:
              name:  backend-secret-key
              key:  SECRET_KEY
        - name:  DB_USER
          valueFrom:
            secretKeyRef:
              name:  postgres-database-auth
              key:  DB_USER
        - name:  DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  postgres-database-auth
              key:  DB_PASSWORD
        - name:  DB_HOST
          valueFrom:
            secretKeyRef:
              name:  postgres-database-auth
              key:  DB_HOST
        - name:  DB_PORT
          valueFrom:
            secretKeyRef:
              name:  postgres-database-auth
              key:  DB_PORT
        - name:  DB_NAME
          valueFrom:
            secretKeyRef:
              name:  postgres-database-auth
              key:  DB_NAME
        - name:  DB_SSL_MODE
          valueFrom:
            secretKeyRef:
              name:  postgres-database-auth
              key:  DB_SSL_MODE
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10000
