apiVersion: v1
kind: Secret
metadata:
  name:  backend-secret-key
stringData:
  SECRET_KEY:  "secret-key"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name:  postgres-database-auth
stringData:
  DB_HOST:  "postgres"
  DB_PORT:  "5432"
  DB_NAME:  "adventcalendar"
  DB_USER:  "adventcalendar"
  DB_PASSWORD:  "adventcalendar"
  DB_SSL_MODE:  "disable"
type: Opaque
