kind: Service
apiVersion: v1
metadata:
  name: admin-api
spec:
  selector:
    app: admin-api
  ports:
    - name: http
      port: 80
      targetPort: http-api
    - name: metrics
      port: 81
      targetPort: http-metrics
