apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-publisher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: email-publisher
    spec:
      restartPolicy: Always
      initContainers:
        - name: init-db
          image: registry.adamkoro.com/adventcalendar/backend/email-publisher-init:latest
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-config
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-config
                  key: MYSQL_PASSWORD
            - name: DB_HOST
              value: "mariadb"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-config
                  key: MYSQL_DATABASE
      containers:
        - image: registry.adamkoro.com/adventcalendar/backend/email-publisher:latest
          imagePullPolicy: Always
          name: email-publisher
          resources:
            requests:
              cpu: "300m"
              memory: "100M"
            limits:
              cpu: "2000m"
              memory: "200M"
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: http-api
              protocol: TCP
            - containerPort: 8081
              name: http-metrics
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret-key
                  key: SECRET_KEY
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-config
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-config
                  key: MYSQL_PASSWORD
            - name: DB_HOST
              value: "mariadb"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-config
                  key: MYSQL_DATABASE
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_VHOST
              value: "/"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
